name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Authenticate with Google Cloud
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Set up Cloud SDK
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # Build and push the Docker image
    - name: Build and Push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/[IMAGE_NAME] --source .
        # Ensure Dockerfile is in the root or adjust the `--source` path accordingly

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy [SERVICE_NAME] \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/[IMAGE_NAME] \
          --region [REGION] \
          --allow-unauthenticated
